RabbitMQ: Being able to configure naming convention of default service
alifcapital/EventBus.RabbitMQ pull request #9
Opened 2024-12-03 12:23 UTC by MirolimMajidov

2024-12-03 12:36 UTC, Tojiddin20 requested changes

2024-12-03 12:36 UTC, Tojiddin20 commented on README.md
> +Keep in mind, the `EventTypeName` and `EventNamingPolicy` options are optional, and if you don't pass it, it will use the event name automatically. But if you
I think you need to complete the sentence after "But if you"

2024-12-03 12:39 UTC, MirolimMajidov commented on README.md
> +Keep in mind, the `EventTypeName` and `EventNamingPolicy` options are optional, and if you don't pass it, it will use the event name automatically. But if you
Fixed

2024-12-03 13:11 UTC, Tojiddin20 approved these changes

2024-12-04 03:09 UTC, merged

2024-12-04 05:03 UTC, akbar-alif commented on tests/UnitTests/Subscribers/EventSubscriberOptionsTests.cs
> +        var eventSettings = new EventSubscriberOptions();
Shouldn't this be in RabbitMq package tests?

2024-12-04 05:17 UTC, MirolimMajidov commented on src/Configurations/BaseEventOptions.cs
> +    private void CalculatorAndSetRoutingKeyIfIsNotAssigned()
Renamed

2024-12-04 05:19 UTC, MirolimMajidov commented on src/Configurations/RabbitMqHostSettings.cs
> +            return eventName;
The event name should come to here. So, when an event has a name, then we could convert it to the correct name based on the configured naming police. Otherwise, we need to just return the default

2024-12-04 08:20 UTC, MirolimMajidov commented on tests/UnitTests/Subscribers/EventSubscriberOptionsTests.cs
> +        var eventSettings = new EventSubscriberOptions();
Those are already on the test project of RabbitMq

2024-12-04 08:31 UTC, akbar-alif reviewed
👍